// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var initialContextValue_000 = /* record */[/* value */0];

function initialContextValue_001(param) {
  return /* () */0;
}

var initialContextValue = /* tuple */[
  initialContextValue_000,
  initialContextValue_001
];

var stateContext = React.createContext(initialContextValue);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = stateContext.Provider;

exports.initialContextValue = initialContextValue;
exports.stateContext = stateContext;
exports.makeProps = makeProps;
exports.make = make;
/* stateContext Not a pure module */
