// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var StateReducer$ReactHooksTemplate = require("../reducers/StateReducer.bs.js");
var StateContextProvider$ReactHooksTemplate = require("./StateContextProvider.bs.js");

function StateValueProvider(Props) {
  var children = Props.children;
  return React.createElement(StateContextProvider$ReactHooksTemplate.make, StateContextProvider$ReactHooksTemplate.makeProps(React.useReducer(StateReducer$ReactHooksTemplate.reducer, StateReducer$ReactHooksTemplate.initialState), children, /* () */0));
}

var make = StateValueProvider;

exports.make = make;
/* react Not a pure module */
