// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var StateContextProvider$ReactHooksTemplate = require("../providers/StateContextProvider.bs.js");

function use(param) {
  return React.useContext(StateContextProvider$ReactHooksTemplate.stateContext);
}

exports.use = use;
/* react Not a pure module */
