// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function reducer(state, action) {
  return /* record */[/* value */state[/* value */0] + action[0] | 0];
}

var initialState = /* record */[/* value */0];

exports.initialState = initialState;
exports.reducer = reducer;
/* No side effect */
