// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var StateValue$ReactHooksTemplate = require("../hooks/StateValue.bs.js");

function Header(Props) {
  var match = StateValue$ReactHooksTemplate.use(/* () */0);
  return React.createElement("header", undefined, "Value: " + String(match[0][/* value */0]));
}

var make = Header;

exports.make = make;
/* react Not a pure module */
