// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Main$ReactHooksTemplate = require("./components/Main.bs.js");
var Header$ReactHooksTemplate = require("./components/Header.bs.js");
var StateValueProvider$ReactHooksTemplate = require("./providers/StateValueProvider.bs.js");

function App(Props) {
  return React.createElement("div", undefined, React.createElement(StateValueProvider$ReactHooksTemplate.make, {
                  children: null
                }, React.createElement(Header$ReactHooksTemplate.make, { }), React.createElement(Main$ReactHooksTemplate.make, { })));
}

var make = App;

exports.make = make;
/* react Not a pure module */
